version: '3'
services:
  redis1:
    image: redis:3
    ports:
      - "6379:6379"
    volumes:
      - ./docker-data/redis-cluster1.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 173.17.0.10
  redis-cluster:
    tty: true
    build:
      context: .
      args:
        redis_version: '3.2.9'
    hostname: server
    depends_on:
      - redis1
    networks:
      app_net:
        ipv4_address: 173.17.0.13
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16
